version: "3.9"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      ID: # Your API HASH from my.telegram.org
      HASH: # Your API ID from my.telegram.org
      TOKEN: # Bot token, get it from @BotFather
